font_options = {
    "Arvo": "'Arvo', serif",
    "Bangers": "'Bangers', cursive",
    "Bevan": "'Bevan', cursive",
    "Black Ops One": "'Black Ops One', cursive",
    "Bowlby One SC": "'Bowlby One SC', cursive",
    "Bungee": "'Bungee', cursive",
    "Caesar Dressing": "'Caesar Dressing', cursive",
    "Chango": "'Chango', cursive",
    "Creepster": "'Creepster', cursive",
    "Days One": "'Days One', sans-serif",
    "Fugaz One": "'Fugaz One', cursive",
    "Lemon": "'Lemon', cursive",
    "Lexend Giga": "'Lexend Giga', sans-serif",
    "Luckiest Guy": "'Luckiest Guy', cursive",
    "Montserrat": "'Montserrat', sans-serif",
    "Noto Sans": "'Noto Sans', sans-serif",
    "Nunito": "'Nunito', sans-serif",
    "Open Sans": "'Open Sans', sans-serif",
    "Permanent Marker": "'Permanent Marker', cursive",
    "Press Start 2P": "'Press Start 2P', cursive",
    "Raleway": "'Raleway', sans-serif",
    "Rammetto One": "'Rammetto One', cursive",
    "Sigmar One": "'Sigmar One', cursive",
    "Slackey": "'Slackey', cursive",
    "Staatliches": "'Staatliches', cursive",
    "Titan One": "'Titan One', cursive"
}